export const VISIBLE_INICIAL = 'VISIBLE_INICIAL';
export const VISIBLE_PROFILE = 'VISIBLE_PROFILE';
export const VISIBLE_NUTRITION = 'VISIBLE_NUTRITION';
export const VISIBLE_TREATMENT = 'VISIBLE_TREATMENT';