export const VISIBLE_INITIAL = 'VISIBLE_INITIAL';
export const VISIBLE_PROFILE = 'VISIBLE_PROFILE';
export const VISIBLE_NUTRITION = 'VISIBLE_NUTRITION';
export const VISIBLE_TREATMENT = 'VISIBLE_TREATMENT';
export const VISIBLE_RECIPES = 'VISIBLE_RECIPES';